### ISSUE TITLE
Channel selection does not work in latest version

### ISSUE THREAD

**Issue by mkeute** [pyreiz/ctrl-stg4000#3]
When I use the download function from stg.api.STG4000, stimulation runs on all channels simultaneously irrespective of the channel index that I passed the function. 
EDIT: The point seems to be that I assumed that deleting the STG4000 object in Python also clears the programming of the stimulator, which is not the case. So, when I set up an STG4000 object, generate and download a stimulation program for channel 0, then overwrite the STG4000 object with a new one and generate and download a stimulation program for channel 1, the old program on channel 0 is maintained. When I call STG4000.start_stimulation then with no arguments, stimulation on both channels is initiated. This problem can be bypassed by calling STG4000.start_stimulation with a list containing the desired channel(s) as an argument. I would suggest including a function that resets the programming of the device upon initialization of a new STG4000 instance, since I find it quite counterintuitive that stimulation programs generated by different instances of STG4000 accumulate rather than overwriting each other.

**Comment by agricolab** [comment]
Thanks for opening the issue.

I am hesitant to add clearing the downloaded files as default behavior during class instantiation or deletion for three reasons. First, this is also the behavior of the MCS GUI, and therefore less non-intuitive if you come from this direction. Second, it clearly shows that in download mode, PC and STG are not coupled, i.e. once downloaded, you can trigger without any USB connection. Third, clearing the downloaded programs during instantiation (or deletion of the object) would prevent the user from recovering a running STG4000 after a reboot of the python kernel or after replugging the USB.

We could add this as an additional kwarg, but the simplest way is probably to add said call of the download method after instantiation and expand the documentation to clarify the behaviour.
